version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "nextjs-code-generator"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-xxxxxxxx"
s3_prefix = "nextjs-code-generator"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []